### PR TITLE
update babel-loader to version 6.0

### PR DESCRIPTION
**Pull request by 21paradox**
same with https://github.com/ruanyf/webpack-demos/pull/10

### CODE REVIEW

**Comment by ruanyf** [comment]
I will start a new branch to test Babel 6 before merging your PR.  It will takes one or two days. 

P.S.  I still think the `exclude` field should be kept for the purpose of templating.

**Comment by 21paradox** [comment]
@ruanyf  thanks!

I will add back exclude

**Comment by ruanyf** [comment]
I pushed a Babel 6 branch based on your PR. Please check it.

https://github.com/ruanyf/webpack-demos/commit/9d3daf162cbda973b077179f30b01d5e3c93a777

**Comment by 21paradox** [comment]
thanks!!

**Comment by ruanyf** [comment]
Thanks for your precious support.

**Pull request closed without merging**
